//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marnie.MultilingualResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marnie.MultilingualResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Age: .
        /// </summary>
        internal static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival: .
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://olek.eu.auth0.com.
        /// </summary>
        internal static string Auth0Endpoint {
            get {
                return ResourceManager.GetString("Auth0Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string ConfirmPassFailText {
            get {
                return ResourceManager.GetString("ConfirmPassFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPasword doesn&apos;t match Password.
        /// </summary>
        internal static string ConfirmPassFailTitle {
            get {
                return ResourceManager.GetString("ConfirmPassFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Detail Page.
        /// </summary>
        internal static string DateDetail {
            get {
                return ResourceManager.GetString("DateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dates.
        /// </summary>
        internal static string DateList {
            get {
                return ResourceManager.GetString("DateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure: .
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gender: .
        /// </summary>
        internal static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6907d36a63c803e.
        /// </summary>
        internal static string ImgurClientId {
            get {
                return ResourceManager.GetString("ImgurClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.imgur.com/3/.
        /// </summary>
        internal static string ImgurEndpoint {
            get {
                return ResourceManager.GetString("ImgurEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey cancelled.
        /// </summary>
        internal static string JourneyCancelled {
            get {
                return ResourceManager.GetString("JourneyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Journeys.
        /// </summary>
        internal static string JourneyList {
            get {
                return ResourceManager.GetString("JourneyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LogInBtn {
            get {
                return ResourceManager.GetString("LogInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again or Sign Up if you don&apos;t have account.
        /// </summary>
        internal static string LogInFailText {
            get {
                return ResourceManager.GetString("LogInFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LogInFailTitle {
            get {
                return ResourceManager.GetString("LogInFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome to Marnie .
        /// </summary>
        internal static string LogInLabel {
            get {
                return ResourceManager.GetString("LogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on your login.
        /// </summary>
        internal static string LoginProgress {
            get {
                return ResourceManager.GetString("LoginProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as .
        /// </summary>
        internal static string LogInStatus {
            get {
                return ResourceManager.GetString("LogInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in.
        /// </summary>
        internal static string LogInStatusErr {
            get {
                return ResourceManager.GetString("LogInStatusErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string LogInSuc {
            get {
                return ResourceManager.GetString("LogInSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find nearest station.
        /// </summary>
        internal static string NearestStationBtn {
            get {
                return ResourceManager.GetString("NearestStationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no others wanting a date on this train.
        /// </summary>
        internal static string NoOneElse {
            get {
                return ResourceManager.GetString("NoOneElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Picture Selected.
        /// </summary>
        internal static string NoPicture {
            get {
                return ResourceManager.GetString("NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://marnie-001-site1.atempurl.com/api.
        /// </summary>
        internal static string OwnApiEndpoint {
            get {
                return ResourceManager.GetString("OwnApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick profile picture from album.
        /// </summary>
        internal static string PickPicture {
            get {
                return ResourceManager.GetString("PickPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture path.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture saved.
        /// </summary>
        internal static string PictureSaved {
            get {
                return ResourceManager.GetString("PictureSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        internal static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchForTrainBtn {
            get {
                return ResourceManager.GetString("SearchForTrainBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpBtn {
            get {
                return ResourceManager.GetString("SignUpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string SignUpFailText {
            get {
                return ResourceManager.GetString("SignUpFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured.
        /// </summary>
        internal static string SignUpFailTitle {
            get {
                return ResourceManager.GetString("SignUpFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up to Marnie.
        /// </summary>
        internal static string SignUpLabel {
            get {
                return ResourceManager.GetString("SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfuly.
        /// </summary>
        internal static string SignUpSuc {
            get {
                return ResourceManager.GetString("SignUpSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other People Looking for a Date.
        /// </summary>
        internal static string TrainPeople {
            get {
                return ResourceManager.GetString("TrainPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Train.
        /// </summary>
        internal static string TrainSearch {
            get {
                return ResourceManager.GetString("TrainSearch", resourceCulture);
            }
        }
    }
}
