//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marnie.MultilingualResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   En typesikker ressourceklasse til søgning efter oversatte strenge etc.
    /// </summary>
    // Denne klasse blev fremstillet automatisk af StronglyTypedResourceBuilder
    // klasse via et værktøj som ResGen eller Visual Studio.
    // Rediger .ResX-filen, og kør derefter ResGen igen for at tilføje eller fjerne et medlem
    // med /str-indstillingen eller byg VS-projektet igen.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returnerer den cachelagrede ResourceManager-forekomst, der anvendes af denne klasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marnie.MultilingualResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tilsidesætter den aktuelle tråds CurrentUICulture-egenskab for alle
        ///   ressourcesøgninger ved hjælp af denne typesikre ressourceklasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Arrival: .
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Your birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Please try again.
        /// </summary>
        internal static string ConfirmPassFailText {
            get {
                return ResourceManager.GetString("ConfirmPassFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til ConfirmPasword doesn&apos;t match Password.
        /// </summary>
        internal static string ConfirmPassFailTitle {
            get {
                return ResourceManager.GetString("ConfirmPassFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til My Dates.
        /// </summary>
        internal static string DateList {
            get {
                return ResourceManager.GetString("DateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Departure: .
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til To:.
        /// </summary>
        internal static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Enter your email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Something went wrong.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til From:.
        /// </summary>
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Select your gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til My Journeys.
        /// </summary>
        internal static string JourneyList {
            get {
                return ResourceManager.GetString("JourneyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til You are logged in.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Login.
        /// </summary>
        internal static string LogInBtn {
            get {
                return ResourceManager.GetString("LogInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Please try again or Sign Up if you don&apos;t have account.
        /// </summary>
        internal static string LogInFailText {
            get {
                return ResourceManager.GetString("LogInFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Login failed.
        /// </summary>
        internal static string LogInFailTitle {
            get {
                return ResourceManager.GetString("LogInFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Wellcome to Marnie .
        /// </summary>
        internal static string LogInLabel {
            get {
                return ResourceManager.GetString("LogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til You are logged in as .
        /// </summary>
        internal static string LogInStatus {
            get {
                return ResourceManager.GetString("LogInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til You are not logged in.
        /// </summary>
        internal static string LogInStatusErr {
            get {
                return ResourceManager.GetString("LogInStatusErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Login successful.
        /// </summary>
        internal static string LogInSuc {
            get {
                return ResourceManager.GetString("LogInSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Your name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Find nearest station.
        /// </summary>
        internal static string NearestStationBtn {
            get {
                return ResourceManager.GetString("NearestStationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Enter your password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Profile picture path.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Route.
        /// </summary>
        internal static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Search.
        /// </summary>
        internal static string SearchForTrainBtn {
            get {
                return ResourceManager.GetString("SearchForTrainBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Sign Up.
        /// </summary>
        internal static string SignUpBtn {
            get {
                return ResourceManager.GetString("SignUpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Please try again.
        /// </summary>
        internal static string SignUpFailText {
            get {
                return ResourceManager.GetString("SignUpFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til An Error has occured.
        /// </summary>
        internal static string SignUpFailTitle {
            get {
                return ResourceManager.GetString("SignUpFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Sign Up to Marnie.
        /// </summary>
        internal static string SignUpLabel {
            get {
                return ResourceManager.GetString("SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Søger efter en lokaliseret streng, der svarer til Account created successfuly.
        /// </summary>
        internal static string SignUpSuc {
            get {
                return ResourceManager.GetString("SignUpSuc", resourceCulture);
            }
        }
    }
}
