using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace Marnie.Model
{
   
    class Person
    {

         public int Id { get; set; }
        
        public string AuthId { get; set; }
    
        public string Name { get; set; }
       
        public DateTime Birthday { get; set; }
       
        public string Gender { get; set; }
        
        public string ProfilPicture { get; set; }

        
        //constructor with only user id generated by Auth0 service
        public Person(string auth_id)
        {
            AuthId = auth_id;
           
        }

        public Person(string authId, string name, DateTime birthday, string gender, string profilPicture)
        {
           AuthId = authId;
            Name = name;
            Birthday = birthday;
            Gender = gender;
            ProfilPicture = profilPicture;
        }

        //public Person(int id, string authId, string name, DateTime birthday, string gender, string profilPicture)
        //{
        //    Id = id;
        //    AuthId = authId;
        //    Name = name;
        //    Birthday = birthday;
        //    Gender = gender;
        //    ProfilPicture = profilPicture;
        //}
    }
}
